spring:
  application:
    name: bareness
  # 创建的 i18n 资源包位置，默认是 messages
  messages:
    basename: i18n/messages
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/practise
#    username: root
#    password: root123
