spring:
  shardingsphere:
    sharding:
      tables:
        user:
          actual-data-nodes: ds0.user0,ds1.user0,ds0.user1,ds1.user1
          # 库分片策略
          database-strategy:
            # 使用复合分片策略
            complex:
              # 分片键（字段）
              sharding-columns: age, birthday
              # 复合分片算法实现类全限定名
              algorithm-class-name: com.personal.demo.algorithm.CustomComplexKeyShardingAlgorithm
          # 表分片策略
          table-strategy:
            complex:
              sharding-columns: age, birthday
              algorithm-class-name: com.personal.demo.algorithm.CustomComplexKeyShardingAlgorithm