spring:
  data:
    elasticsearch:
      repositories:
        enabled: true            # 启用 ES 本地存储库
  # elasticsearch:
   # rest:
      #uris: localhost:9200      # 配置 ES 地址
      # username: 123
      # password: 123
      # connection-timeout: 1000
      # read-timeout: 30000