rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producerGroup     # 生产者所属组名
  consumer:
    topic: testTopic         # 消费主题
    group: consumerGroup     # 消费者所属组名
    pull-batch-size: 5       # 每次消费拉取消息数量