spring:
  rocketmq:
    namesrvAddr: localhost:9876
    producerGroup: TestProducer
    consumerGroup: TestConsumer
    # SpringBoot 使用 RocketMQ 操作同普通方式相同，未展示任何特殊注解
    # 无非就是将一些信息配置在 yaml 文件，因此不展示代码编写