logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

server:
  port: 80

spring:
  redis:
#    host: localhost
#    port: 7003
    password: corgi       # master 节点密码，集群或哨兵模式中若 master 设置了密码，除了配置文件配置密码外，此处也要填写密码
    cluster:              # 集群配置
      nodes:              # 集群所有节点地址
        - localhost:7001
        - localhost:7002
        - localhost:7003
        - localhost:8001
        - localhost:8002
        - localhost:8003
#    sentinel:
#      master: mymaster    # master 名称，对应 sentinel.conf 声明的名称
#      nodes:              # Sentinel 所有实例地址
#        - lcoalhost:8001
#        - lcoalhost:8002
#        - lcoalhost:8003
#      password: corgi    # Sentinel 密码
